### ISSUE TITLE
[Bug]: Migration failed

### ISSUE THREAD

**Issue by chisomgbata** [tursodatabase/turso-driver-laravel#1]
### What happened?

I cannot setup turso and laravel, installed the libsql and the turso-driver-laravel, but on running php artisan migrate i get 

`  Call to a member function fetchArray() on array

  at vendor/tursodatabase/turso-driver-laravel/src/Database/LibSQLPDOStatement.php:53`

### How to reproduce the bug

I cannot setup turso and laravel, installed the libsql and the turso-driver-laravel, but on running php artisan migrate i get 

`  Call to a member function fetchArray() on array

  at vendor/tursodatabase/turso-driver-laravel/src/Database/LibSQLPDOStatement.php:53`

### Package Version

1.0.4

### PHP Version

8.3.7

### Laravel Version

11.10.0

### Which operating systems does with happen with?

Linux

**Comment by darkterminal** [comment]
Thank you for reporting this issue...

I will check it and fix it. Sorry for late response...

**Comment by darkterminal** [comment]
Hi @chisomgbata I just fix the migration. You can update to latest version :tada:
