### ISSUE TITLE
[Bug]: Non English character

### ISSUE THREAD

**Issue by johnqiuwan** [tursodatabase/turso-driver-laravel#18]
### What happened?

The database driver not be able to insert non English character. 
I have checked that sqlite is utf-8.

In addition, I tried using  sqlite instead of turso-driver-laravel , and it has no issue on non English characters.

### How to reproduce the bug

fresh install the package and try insert non English character.

Sample code:

 DB::table('categories')->insert([       
    ['name' => '안녕하세요', 'description' => 'Database related articles'],
 ]);

### Package Version

1.0

### PHP Version

8.2.0

### Laravel Version

11.9

### Which operating systems does with happen with?

macOS

**Comment by darkterminal** [comment]
This issues is fix in latest version, please update the dependency for changes. Thank you, feel free to report if you've any trouble related to this driver.
