### ISSUE TITLE
[Bug]: Undefined array key "rows"

### ISSUE THREAD

**Issue by mpociot** [tursodatabase/turso-driver-laravel#2]
### What happened?

When running `php artisan migrate:fresh` an exception gets thrown:

```
Undefined array key "rows"

at vendor/tursodatabase/turso-driver-laravel/src/Database/LibSQLSchemaBuilder.php:51
     47▕     protected function dropAllTriggers(): void
     48▕     {
     49▕         $statement = $this->connection->getPdo()->query($this->grammar()->compileDropAllTriggers());
     50▕
  ➜  51▕         collect($statement['rows'])->each(function (array $query) {
     52▕             $this->connection->select($query[0]);
     53▕         });
     54▕     }
     55▕
```

### How to reproduce the bug

Setup a Laravel project to use the Turso Laravel driver and run `php artisan migrate:fresh`

### Package Version

^1.0

### PHP Version

8.3.8

### Laravel Version

11.10.0

### Which operating systems does with happen with?

macOS

**Comment by darkterminal** [comment]
Thank you for reporting this issue...
I will check it and fix it. Sorry for late response.

**Comment by darkterminal** [comment]
Hi @mpociot I just fix the migration. You can update to latest version 🎉
